image: Visual Studio 2019

matrix:
  fast_finish: true

platform:
- x64

# http://www.appveyor.com/docs/installed-software
environment:
  BOOSTDIR: C:\Libraries\boost_1_73_0
  PYTHONDIR: "C:\\Python38-x64"
  QTDIR: "C:\\Qt\\5.14\\msvc2017_64"
  PATH: "%QTDIR%\\bin;%PYTHONDIR%;%PYTHONDIR%\\Scripts;%BOOSTDIR%\\lib64-msvc-16.0;%PATH%"
  PYTHONPATH: "%PYTHONDIR%;%PYTHONDIR%\\Lib;%PYTHONDIR%\\Lib\\site-packages;%PYTHONDIR%\\DLLs"
  PYEXE: "%PYTHONDIR%\\python.exe"
  PYLIB: "%PYTHONDIR%\\libs\\python38.lib"
build:
  parallel: true

init:
- echo "BornAgain init" %CD%
- echo %PATH%

install:
- git submodule -q update --init

before_build:
- echo "BornAgain before_build" %CD%
- dir  C:\Python38-x64\libs
- python -m pip install --upgrade pip
- python -m pip install numpy
- mkdir C:\projects\deps
- C:\cygwin\bin\wget -q http://apps.jcns.fz-juelich.de/src/WinLibs/libgsl.win64.zip -O %temp%\libgsl.zip
- 7z x %temp%\libgsl.zip -oC:\projects\deps
- dir C:\projects\deps
- dir C:\projects\deps\include
- C:\cygwin\bin\wget -q http://apps.jcns.fz-juelich.de/src/WinLibs/libtiff.win64.zip -O %temp%\libtiff.zip
- 7z x %temp%\libtiff.zip -oC:\projects\deps
- dir C:\projects\deps
- dir C:\projects\deps\include
- C:\cygwin\bin\wget -q http://apps.jcns.fz-juelich.de/src/WinLibs/libcblas.win64.zip -O %temp%\libcblas.zip
- 7z x %temp%\libcblas.zip -oC:\projects\deps
- dir C:\projects\deps
- dir C:\projects\deps\include
- C:\cygwin\bin\wget -q http://apps.jcns.fz-juelich.de/src/WinLibs/libfftw3.win64.zip -O %temp%\libfftw3.zip
- 7z x %temp%\libfftw3.zip -oC:\projects\deps
- dir C:\projects\deps
- dir C:\projects\deps\include
- set CMAKE_URL="https://cmake.org/files/v3.17/cmake-3.17.2-win64-x64.zip"
- appveyor DownloadFile %CMAKE_URL% -FileName %temp%\cmake.zip
- 7z x %temp%\cmake.zip -oC:\projects\deps > nul
- move C:\projects\deps\cmake-* C:\projects\deps\cmake # Move to a version-agnostic directory
- set PATH=C:\projects\deps\lib;C:\projects\deps\cmake\bin;%PATH%

build_script:
- echo "BornAgain build_script" %CD%
- echo %PATH%
- echo "PYEXE" %PYEXE% "PYLIB" %PYLIB%
- mkdir build
- cd build
- cmake --version
- cmake -G "Visual Studio 16 2019" -DBOOST_ROOT=%BOOSTDIR% -DPython_LIBRARY=%PYLIB% -DPython_EXECUTABLE=%PYEXE% -DCMAKE_INCLUDE_PATH=C:/projects/deps/include ..
- cmake --build . --config Release

test_script:
- echo "BornAgain test_script" %CD%
- echo %PATH%
- echo %PYTHONPATH%
- echo %PYTHONHOME%
- ps: >-
    ctest -LE Fullcheck --output-on-failure

    if (-not $?) {

        type Testing/Temporary/LastTest.log

        throw "tests failed"

    }

on_failure:
- echo "Going RDP"
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
