stages:
  - build

mac:
  tags:
  - MacOS
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ctest --output-on-failure
    # - cpack .
  artifacts:
    paths:
    - build/*zip
    expire_in: 10 days

windows:
  tags:
  - Windows
  stage: build
  script:
    - New-Item -ItemType "directory" -Confirm:$false -Force:$true -Name "build"
    - $Env:Path
    - cd build
    - cmd.exe "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
    - cmake --version
    - cmake -G "Visual Studio 16 2019" -A x64 -T host=x64 -DLIB_MAN=OFF -DQTDIR=C:/Qt/5.14.1/msvc2017_64 -DCPACK_IFW_ROOT=C:\Qt\Tools\QtInstallerFramework\3.2 -B. ..
    - cmake --build . --config Release
    - Get-Location
    - dir
    - dir bin
    - dir bin\Release
    - dir core
    - dir core\Release
    - dir ftest
    - dir gui
    - dir gui\Release
    - dir main
    - dir main\Release
    - dir utest
    - dir utest\Release
    - dir utest\core
    - dir utest\core\linked
    - dir utest\core\linked\Release
    - ctest -C Release --output-on-failure
    - cpack -C Release --verbose
  artifacts:
    paths:
    - build/*.exe
    - build/bin/Release/*.dll
    - build/bin/Release/*.exe
    expire_in: 1 week

native_Debian_clang:
  tags: &native
  - Debian
  before_script: &debian_clang
    - export CC=clang; export CXX=clang++
    - cmake --version
    - clang --version
  stage: build
  script: &native_scr
    - pwd
    - mkdir build
    - cd build
    - cmake .. # -DWERROR=ON
    - make -j6
    - ctest -j6 --output-on-failure
