language: cpp
sudo: required

#services:
#- docker

 
#env:
#- BUILD_TYPE=Release

matrix:
  include:
    - os: linux
      services: docker
      env: BUILD_TYPE=Release
#    - os: osx
#      osx_image: xcode7.3
#      env: BUILD_TYPE=Release

before_install:
- chmod +x .travis/*/*.sh

install:
- .travis/${TRAVIS_OS_NAME}/install.sh

script:
- .travis/${TRAVIS_OS_NAME}/build.sh
- .travis/${TRAVIS_OS_NAME}/test.sh
- .travis/${TRAVIS_OS_NAME}/pack.sh


after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh *.deb

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
